// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruxdvfuetvhuybjwaaka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1eGR2ZnVldHZodXliandhYWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0Mjk1NjYsImV4cCI6MjA0OTAwNTU2Nn0.koQI_2rpVkU5W6Ta1iqJ4iMpqq5Aecqx_rHg4NPsPpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);